#ifndef CBINDGEN_BINDINGS_H
#define CBINDGEN_BINDINGS_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#if defined(TARGET_OS_ANDROID)
/**
 * AndroidBitmap functions result code.
 */
typedef int32_t _bindgen_ty_1;
#endif

#if defined(TARGET_OS_ANDROID)
/**
 * Bitmap pixel format.
 */
typedef uint32_t AndroidBitmapFormat;
#endif

#if defined(TARGET_OS_ANDROID)
/**
 * Operation was successful.
 */
#define ANDROID_BITMAP_RESULT_SUCCESS 0
#endif

#if defined(TARGET_OS_ANDROID)
/**
 * Bad parameter.
 */
#define ANDROID_BITMAP_RESULT_BAD_PARAMETER -1
#endif

#if defined(TARGET_OS_ANDROID)
/**
 * JNI exception occured.
 */
#define ANDROID_BITMAP_RESULT_JNI_EXCEPTION -2
#endif

#if defined(TARGET_OS_ANDROID)
/**
 * Allocation failed.
 */
#define ANDROID_BITMAP_RESULT_ALLOCATION_FAILED -3
#endif

#if defined(TARGET_OS_ANDROID)
/**
 * No format.
 */
#define AndroidBitmapFormat_ANDROID_BITMAP_FORMAT_NONE 0
#endif

#if defined(TARGET_OS_ANDROID)
/**
 * Red: 8 bits, Green: 8 bits, Blue: 8 bits, Alpha: 8 bits.
 */
#define AndroidBitmapFormat_ANDROID_BITMAP_FORMAT_RGBA_8888 1
#endif

#if defined(TARGET_OS_ANDROID)
/**
 * Red: 5 bits, Green: 6 bits, Blue: 5 bits.
 */
#define AndroidBitmapFormat_ANDROID_BITMAP_FORMAT_RGB_565 4
#endif

#if defined(TARGET_OS_ANDROID)
/**
 * Deprecated in API level 13. Because of the poor quality of this configuration, it is advised to use ARGB_8888 instead.
 */
#define AndroidBitmapFormat_ANDROID_BITMAP_FORMAT_RGBA_4444 7
#endif

#if defined(TARGET_OS_ANDROID)
/**
 * Alpha: 8 bits.
 */
#define AndroidBitmapFormat_ANDROID_BITMAP_FORMAT_A_8 8
#endif

#if defined(TARGET_OS_IOS)
void native_generate_qr_with_string(const int8_t *string,
                                    uint8_t *bytes_in,
                                    uintptr_t bytes_in_size,
                                    unsigned int width,
                                    unsigned int height,
                                    const int8_t *color,
                                    const int8_t *background_color);
#endif

#if defined(TARGET_OS_IOS)
void native_generate_qr_with_bytes(const uint8_t *bytes,
                                   uintptr_t size,
                                   uint8_t *bytes_in,
                                   uintptr_t bytes_in_size,
                                   unsigned int width,
                                   unsigned int height,
                                   const int8_t *color,
                                   const int8_t *background_color);
#endif

#if defined(TARGET_OS_ANDROID)
void Java_io_nstudio_nativescript_plugins_qr_Qr_nativeGenerateQRWithBytes(JNIEnv env,
                                                                          JClass,
                                                                          jbyteArray bytes,
                                                                          JObject bitmap_in,
                                                                          jint width,
                                                                          jint height,
                                                                          JString color,
                                                                          JString background_color);
#endif

#endif /* CBINDGEN_BINDINGS_H */
