[package]
name = "web-server-native"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix-files = "0.6.6"
actix-ws = "0.3.0"
actix-cors = "0.7.0"
parking_lot = "0.12.3"
futures = "0.3.31"
futures-util = "0.3.31"
bytestring = "1"
tokio = {version = "1.41.1",  features = ["rt", "rt-multi-thread"]}